### ISSUE TITLE
How do I change sensor update interval?

### ISSUE THREAD

**Issue by mkanet** [jdeath/Roblox-Homeassistant#1]
Thank you for making this integration.  Unfortunately it's respective sensors are unusably slow.. even with just 4 Roblox friends.  By the time the sensor updates, the user has already left the game or playing a different game.  Surely there has to be a way to change the polling interval.  The Steam integration doesn't have this issue.

**Comment by jdeath** [comment]
Edit line 34 of custom_components/roblox/sensor.py

It checks each every 5 minutes, so if you have 4 it will take 20 minutes to cycle though them. Change it to whatever you want. I probably would not go less than 30 seconds...

The steam integration was written by professionals, roblox was done by me!

**Comment by mkanet** [comment]
Thank you @jdeath!  I just changed the value from `5` to `.5`.  Now, it's more useful ...enough to keep this integration on my setup.  Out of curiosity what's the side-effect of reducing below `.5`?  Why not `.25`?  Is it because it will utilize too many system resources to poll that frequently?

```
BASE_INTERVAL = timedelta(minutes=.5)
```
Also, any idea what the images (marked with red color below) are supposed to be?  It looks like the image they are supposed to display is corrupted?  Maybe they are supposed to be the player's game background?

![107-01-2023 at 02 26 36 PM](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/7da1a667-ff5a-4912-a509-47e2e497e37f)

![2](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/99c89efe-e977-4eae-9132-3346b3d0367a)

**Comment by jdeath** [comment]
Just you ping the roblox servers alot. If you are willing to risk getting shut off, you can reduce it as much as you like.

I think they may have changed the API so the game image is not being pulled in correctly. I will have to look into it.

**Comment by mkanet** [comment]
> Just you ping the roblox servers alot. If you are willing to risk getting shut off, you can reduce it as much as you like.
> 
> I think they may have changed the API so the game image is not being pulled in correctly. I will have to look into it.

https://create.roblox.com/docs/reference/engine/classes/HttpService#GetAsync

"For each Roblox game server, there is a limit of **_500 HTTP requests per minute_**. Exceeding this may cause request-sending functions to stall entirely for about 30 seconds."

They can accommodate much faster polling than the default `5 minutes`; or even `.5 minutes`.  Also, even if it exceeds their limit of 500 requests per minute, it will just stall for about 30 seconds.

PS:  I just changed the polling from `.5` to `.25` for 4 users.  Now, it's pretty close to instant ...much better than 20 minutes.

**Comment by jdeath** [comment]
Cool. I just pushed an update which should get the game image properly now.

**Comment by mkanet** [comment]
> Cool. I just pushed an update which should get the game image properly now.

You are AWESOME!  Thank you!  

Just one thing... I know you didn't make the Steam Card... but, do you know if it's possible to NOT display the `game-background placeholder` when there is no game background (see red in screenshot below)?  It doesn't look like it even belongs there.

![3](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/e04f947a-6483-4f73-8763-ad6ced9db62c)

This is what it looks like with a single entity; even with your more recent update.  It looks like something is broken or not displaying correctly for the placeholder:

![4](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/a8a9bbee-9d3b-453a-a8f8-8857cc4ec7f0)

**Comment by jdeath** [comment]
No, I don't know if you cannot show background if not online. I probably need to set the image URL to something with a single pixel or something, as the card may always expect an image. Not quite sure how to do that. 

I just use an entity row, not the steam card. You do not get an image, but I find it distracting always.

`
```type: entities
entities:
  - type: attribute
    entity: sensor.roblox_XXXXXX
    attribute: game
```

**Comment by mkanet** [comment]
> No, I don't know if you cannot show background if not online. I probably need to set the image URL to something with a single pixel or something, as the card may always expect an image. Not quite sure how to do that.
> 
> I just use an entity row, not the steam card. You do not get an image, but I find it distracting always.
> 
> `
> 
> ```
> entities:
>   - type: attribute
>     entity: sensor.roblox_XXXXXX
>     attribute: game
> ```

Yeah, I was using a regular entity card before I started using the steam card.  The Steam card looks much nicer IMO; at least when the user is in a game.

**Comment by mkanet** [comment]
This is what the background image placeholder looks like for the Steam Integration on the Steam card, it looks like a cleaner-looking "hyphen" symbol instead:

![5](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/5a459152-5307-4c83-ac8a-53e8ee603187)

**Comment by mkanet** [comment]
@jdeath I was able to fix the steam card to NOT display the hyphen symbol for Steam HA entities.  Now it looks perfect.
![image](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/afc2c751-a426-4d07-b973-04647b04aba6)

  All I did was change line 189 of `kb-steam-card.js`

From: `<div class="kb-steam-value">${i.attributes.game||"-"}</div>`
To: `<div class="kb-steam-value">${i.attributes.game||i.state}</div>`

.
.

**The only remaining issue your Roblox Integration displaying the weird broken image:**
![8](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/12fa43db-86ae-43e9-b5c7-0377cf1bb7e5)

Could you _please_ see if you can fix this so the Steam card will work correctly with your integration?

**Comment by jdeath** [comment]
I was able to make a work around. This is probably the best I can do.

First download a 1x1 pixel image to your www\ directory
https://upload.wikimedia.org/wikipedia/commons/c/ca/1x1.png

You may need to find a black one.

At line 190 in sensor.py you will see this:
```
if self._game_id is not None:
   attr["game_id"] = self._game_id
   attr["place_id"] = self._placeId
   attr["universe_id"] = self._universeId
   # game_url = f"{roblox_API_URL}{self._game_id}/"
   attr["game_image_header"] = self._game_image_header
   attr["game_image_main"] = self._game_image_main
```

add 3 more lines (the esle statement), so it looks like this. Just replace the domain with your domain name.
```
if self._game_id is not None:
   attr["game_id"] = self._game_id
   attr["place_id"] = self._placeId
   attr["universe_id"] = self._universeId
    # game_url = f"{roblox_API_URL}{self._game_id}/"
   attr["game_image_header"] = self._game_image_header
   attr["game_image_main"] = self._game_image_main
else:
   attr["game_image_header"] = "https://homeassistant.your.domain/local/1x1.png"
   attr["game_image_main"] = "https://homeassistant.your.domain/local/1x1.png"
```

**Comment by mkanet** [comment]
Thank you for everything.  It all looks much more polished with no weird issues.  I made a completely transparent 1x1 "dot"; which is invisible in html.  I also changed the originally Steam card red color (indicating online) to green.  That makes more sense to me for someone that's online.

I appreciate all your help making this perfect and polished... much much nicer than how it was yesterday; and, updates instantly... even with 4 or more people.

![8](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/e2119a96-f1d9-4fe9-bcba-5f30ed9862ad)

Hopefully this will continue to work for a while without it breaking.

**Comment by jdeath** [comment]
Nice, how did you change the dot to green? That is much better.

**Comment by mkanet** [comment]
> Nice, how did you change the dot to green? That is much better.

Sorry, it took me so long to reply back.  Open the file:  `config\www\community\kb-steam-card.js` _(or wherever you have installed kb-steam-card)_ and change:

```js
      .kb-steam-multi.online::before,
      .kb-steam-multi.snooze::before {
        box-shadow: 0 0 1em #1c1c17, 0 0 1em #ff4242;
        background: #ff4f4f;
      }
```
to
```js

      .kb-steam-multi.online::before {
        box-shadow: 0 0 1em #1c1c17, 0 0 1em #008F00;
        background: #00C500;
      }

      .kb-steam-multi.snooze::before {
        box-shadow: 0 0 1em #1c1c17, 0 0 1em #314F8C;
        background: #3E61B2;
      }

      .kb-steam-multi.away::before {
        box-shadow: 0 0 1em #1c1c17, 0 0 1em #AF8600;
        background: #FFC700;
      }
```

Online = Green
Snooze = Blue
Away =   Yellow

Below is an example screenshot... However, I didn't have any friends that display Snooze status (blue) at the time I took this screenshot:
![image](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/61793b42-ef22-4572-829c-f2c6de9ea9ee)

**EDIT:**  This is what the snooze color looks like:
![image](https://github.com/jdeath/Roblox-Homeassistant/assets/811008/f050b75e-08e2-440c-9fc3-735cbaa9c122)
