### ISSUE TITLE
URL is not accepted as a valid repository in Home Assistant

### ISSUE THREAD

**Issue by siw1973** [jdeath/Roblox-Homeassistant#3]
When using the URL below it is rejected, with different errors on occassion, when adding as a repository.

https://github.com/jdeath/Roblox-Homeassistant.git

ERROR 1
https://github.com/jdeath/Roblox-Homeassistant.git is not a valid add-on repository

ERROR 2
Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/jdeath/Roblox-Homeassistant.git /data/addons/git/513fe336 stderr: 'Cloning into '/data/addons/git/513fe336'... POST git-upload-pack (175 bytes) error: could not lock config file /data/addons/git/513fe336/.git/config: No such file or directory fatal: could not set 'core.repositoryformatversion' to '0' '

**Comment by jdeath** [comment]
use https://github.com/jdeath/Roblox-Homeassistant

**Comment by siw1973** [comment]
I'm still getting the below error : 

https://github.com/jdeath/Roblox-Homeassistant.git is not a valid add-on repository

I'm running the following config on a Synology Virtual Machine Manaager HASSOS instance : 

Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest

I have added a number of additional Add On Repositories, but none in about 6 months.

**Comment by jdeath** [comment]
Not sure. I removed it and added back in and it works fine with no error. Be sure not to add the .git to the end and set the category to integration.

**Comment by siw1973** [comment]
I'm not sure what you mean by setting an Add On as an Integration when adding a Repository.

<img width="960" alt="image" src="https://github.com/jdeath/Roblox-Homeassistant/assets/7414936/e494d763-2fd8-47aa-9081-dc7ba1eccf64">

I add the repository URL and the failure as per the one above.

<img width="956" alt="image" src="https://github.com/jdeath/Roblox-Homeassistant/assets/7414936/ce339ec3-bfe4-4ca7-873d-59f05a7e925d">

**Comment by siw1973** [comment]
I'm an idiot...... All sorted......

**Comment by jdeath** [comment]
Ahh good. Yes, need to add in HACS not in Add Ons...
